Skip to content
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 
@anilpalankar 
Learn Git and GitHub without any code!
Using the Hello World guide, you’ll start a branch, write comments, and open a pull request.


redashu
/
febday5eyazure
1
00
 Code Issues 0 Pull requests 0 Actions Projects 0 Wiki Security Insights
febday5eyazure/ashudep1.yml
@redashu redashu day 5 v1
b2942b9 1 hour ago
46 lines (46 sloc)  785 Bytes
  
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ashudepday5
  name: ashudepday5
  namespace: ashutoshh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ashudepday5
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ashudepday5
    spec:
      containers:
      - image: dockerashu/eyappday5:v1
        name: eyappday5
        imagePullPolicy: Always
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ashudepsvc1
  name: ashudepsvc1
  namespace: ashutoshh
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ashudepday5
  type: NodePort
status:
  loadBalancer: {}
© 2020 GitHub, Inc.
Terms
Privacy
Security
Status
Help
Contact GitHub
Pricing
API
Training
Blog
About
